### ISSUE TITLE
Zauber 1.2.1 is incompatible with Nebula 6.0.0 on Minecraft 1.20.4

### ISSUE THREAD

**Issue by Poopooracoocoo** [Dev0Louis/Zauber#2]
Downgrading Nebula to 5.2.0 works: https://modrinth.com/mod/nebula/version/5.2.0+1.20.4

**Comment by Dev0Louis** [comment]
Yeah you are correct, support for Nebula 6 has not been released yet. That is because I am working on a bigger update adding upon other things rituals. 
I cant give an exact time when the update will release, but it will have Nebula 6 support.

Thanks for showing interest in the mod. If you need a version that works with Nebula 6 right now, let me know and I can release it. (Without the rituals of course as they are not finished yet)

**Comment by Dev0Louis** [comment]
Zauber 1.3.2 is out and it is compaitable with Nebula v6. Have fun
